services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  web_server:
    container_name: server

    volumes:
      - ./server:/var/www/html

    build:
      context: ./server
      dockerfile: Dockerfile

    restart: always

    ports:
      - 8000:80
      
    depends_on:
      - db